import { Inter } from "next/font/google";
import "./globals.css";
import 'react-multi-carousel/lib/styles.css';
import {Montserrat} from 'next/font/google'
import { ReduxProvider } from "../redux/reduxProvider";
import Providers from "./provider";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import Loader from "@/componants/loader/Loader";
import Navbar from "@/componants/navbar/Navbar";
import Footer from "@/componants/footer/Footer";


const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  weight: '400',
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReduxProvider>
            <Toaster position="bottom-center"/>
            <Suspense fallback={<Loader/>}>
              <Navbar/>
              {children}
              <Footer/>
            </Suspense>
        </ReduxProvider>
      </body>
    </html>
  );
}
