import { Inter } from "next/font/google";
import "./globals.css";
import 'react-multi-carousel/lib/styles.css';
import {Montserrat} from 'next/font/google'
import { ReduxProvider } from "./redux/reduxProvider";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  weight: '400',
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReduxProvider>
        {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
